# Config file for specifying the ID of each Mia Hand force sensor. These IDs are 
# used by the ROS driver to publish the sensor outputs over the appropriate 
# fields of the dedicated topic. Therefore, it should be changed only in case, 
# for any hand manufacturing issue, the output of any sensor was not published 
# over the expected topic field (i.e., if it was observed that the output of two
# sensors is swapped).

# Default mapping:
#
# thumb_normal_id: 4
# thumb_tangential_id: 3
# index_normal_id: 1
# index_tangential_id: 2
# mrl_normal_id: 5
# mrl_tangential_id: 0

thumb_normal_id: 4
thumb_tangential_id: 3
index_normal_id: 5
index_tangential_id: 0
mrl_normal_id: 1
mrl_tangential_id: 2
